project:
  type: website

website:
  title: "Global Frost Events Benchmark Dataset"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events/index.qmd
        text: Events
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



